### ISSUE TITLE
API cleanup

### ISSUE THREAD

**Issue by wilsoncusack** [base-org/op-viem#122]
- consider changing writeFinalize... to have `args` and `withdrawal` within to match the API of the other functions https://github.com/base-org/op-viem/blob/main/src/actions/wallet/L1/writeFinalizeWithdrawalTransaction.ts#L19
- [depositETH](https://github.com/base-org/op-viem/blob/main/src/actions/wallet/L1/writeDepositETH.ts) args doesn't include amount or value, you just pass value. But withdraw [does](https://github.com/base-org/op-viem/blob/main/src/types/withdrawTo.ts#L12) take an amount arg. This matches the smart contracts, but is kind of weird. We should consider picking one. Passing amount is probably more clear.

**Comment by wilsoncusack** [comment]
lmk if you have thoughts @zencephalon

**Comment by zencephalon** [comment]
Consider using a `mint` arg instead of `value` to denote the amount to mint on the L2
