### ISSUE TITLE
Consider removing `value` from args for writeDepositTransaction and add `args.mint`

### ISSUE THREAD

**Issue by wilsoncusack** [base-org/op-viem#136]
Consider adding `mint` here https://github.com/base-org/op-viem/blob/b9f1b8ba7c969ad281ec9952a4940aa161125f38/src/actions/wallet/L1/writeDepositTransaction.ts#L11C5-L17

as what is paid to this transaction will be minted to the user on L2. This would replace viem's normal `value` args, and we would set `value = args.mint`

**Comment by Sabnock01** [comment]
Ok if I take this one?
