### ISSUE TITLE
Consider wallet decorators unique to L1 and. L2

### ISSUE THREAD

**Issue by wilsoncusack** [base-org/op-viem#18]
The actions users take on L1 -> L2 and entirely different than L2 -> L1. 

E.g. Going L1 -> L2 is a deposit and takes minutes, but going L2 -> L1 is a withdraw and takes days. Replaying messages happens on L2. etc. 

For each type of action, we want to have good types on client chain, the toChain in the transaction, and their relation. E.g. we only want someone to call deposit from an L1 to a valid L2. 

If every function has a generic Chain and TTochain which enforce these rules, these type enforcements bubble up to the decorator. There are really two enforcements: actions for the L2 and actions for the L1. 

It may make sense to just have entirely different decorators for these wallet actions. Users have to do a little more work, but it's a more clear and safe experience `walletClient(...).extend(OPStackL2Actions)` or `walletClient(...).extend(OPStackL1Actions)`

**Comment by roninjin10** [comment]
I actually have the opposite view on this. I think the API should always just be `bridge({to, from, bridgStrategy})` where the bridge strategy is what specifies nuances such as one takikng minutes and the other taking days. 

However if I was actively building this myself I would start with seperate deposits and withdrawals and get that easier api right first before trying to generalize more

**Comment by wilsoncusack** [comment]
done
