### ISSUE TITLE
simulateDepositTransaction

### ISSUE THREAD

**Issue by wilsoncusack** [base-org/op-viem#27]

**Comment by wilsoncusack** [comment]
I also think it would be cool to have like simulateL2ResultOfDepositTransaction which uses the L1 simulation to figure out the L2 transaction and simulate it. Only downside is we can't (?) simulate the ETH balance minted to them as a result of the L1 tx.

**Comment by zencephalon** [comment]
Added in https://github.com/base-org/op-viem/pull/147
