### ISSUE TITLE
publicClient: getSecondsToFinalizable

### ISSUE THREAD

**Issue by wilsoncusack** [base-org/op-viem#30]
Thinking it might be nice to have a function that tells you how long until a withdraw can be finalized. Can use `L2_ORACLE.getL2Output(_l2OutputIndex).timestamp` and `L2_ORACLE.FINALIZATION_PERIOD_SECONDS()`

**Comment by roninjin10** [comment]
I think (don't remember) this exists on the current sdk so we would need to add this to fully establish this as the new sdk

**Comment by wilsoncusack** [comment]
#78
