### ISSUE TITLE
Read functions 

### ISSUE THREAD

**Issue by wilsoncusack** [base-org/op-viem#31]
Some functions for making call requests to specific OP Contract methods. Still thinking if worth it, but time of mind
- minimumGasLimit 
- isOutputFinalized
- finalizedWithdrawals
- provenWithdrawals

**Comment by roninjin10** [comment]
- What does isOutputFinalized do that a more general getMessageStatus wouldn't do?
- Estimate l2Gas estimate l1Gas are some useful hooks
- on op goerli only there is a need for a getChainCOnfig hook

None of this stuff needs to be added though keeping the API more minimal to just the bridge API you need to use a bridge and then adding stuff later I think is better approach than trying to make the perfect SDK in one swing

**Comment by roninjin10** [comment]
finalizedWithdrawals and provenWithdrawals you kinda need an indexer to get those

**Comment by wilsoncusack** [comment]
> finalizedWithdrawals and provenWithdrawals you kinda need an indexer to get those

The optimismPortal has methods for getting just one

**Comment by wilsoncusack** [comment]
provenWithdrawals is done in #78

**Comment by wilsoncusack** [comment]
closing for smaller
