### ISSUE TITLE
Document code coverage

### ISSUE THREAD

**Issue by wilsoncusack** [base-org/op-viem#35]
We should have a github workflow that checks this

**Comment by roninjin10** [comment]
Ooops my bad I totally dropped ball on adding this

A workflow of how I do this is here: https://github.com/evmts/evmts-monorepo/blob/main/.github/workflows/test.yml
And then setting coverage thresholds in vitest config: https://github.com/evmts/evmts-monorepo/blob/main/core/vitest.config.ts
